### ISSUE TITLE
[Workshop Review] MicroBit: Coding with mini computers

### ISSUE THREAD

**Issue by brettefoster** [NuevoFoundation/workshops#201]
Great work overall! Below are issues found and some notes. 

Doubles: In the Double definition remove "messy" as it is potentially confusing and has a negative connotation. Perhaps change to "Unlike integers, the double data type does support use of a decimal"? 

Strings: Remove "MICROSOFT" as we do not want to imply bias in the lesson?

Characters: Indicates single quote usage but example is using double quotes. 

Math Operations: The starting variables are not defined for the examples given. Also, to make the examples more clear, we should introduce variable 'c' for the answer so the students are not confused by 'a' being both an operation component and operation answer. 

Print Statements: The strings for console.log and alert explain what the browser will do but it is not clear to the reader what "prompt" will do. 

Loops: There are operations used in the example that are not covered above (e.g., "--"). Also, the description states "The alert() function you see..." but there are no functions defined and there are multiple blocks with "alert()". 

Your turn: Should have some links to recommended tutorials?

**Comment by ozhang22** [comment]
#321
