### ISSUE TITLE
[Workshop review] Spy Game

### ISSUE THREAD

**Issue by brettefoster** [NuevoFoundation/workshops#202]
Great lesson! I think students will engage well with this approach. 

One minor feedback is on the "can this password be hacked?" section. The "answers" button takes me to the summary page and there was no direct feedback on which questions I had answered correctly (I had to go back and very myself). I was expecting to see the same list of questions with the answers populated (and indicating which ones the user answered correctly, if possible). It would also be good if the answers page reinforced the earlier teachings by explaining why each example is a strong or weak password.

**Comment by ozhang22** [comment]
#321
