### ISSUE TITLE
Update Workshops footer "2019" to "2021"

### ISSUE THREAD

**Issue by jeremiahjordanisaacson** [NuevoFoundation/workshops#204]
"© Copyright **2019**, All Rights Reserved by Nuevo Foundation, a 501(c)(3) nonprofit." should be updated to the current year "**2021**"

**Comment by jruales** [comment]
@chyoung93 there are two instances of the year, in the English and Spanish text: https://github.com/NuevoFoundation/workshops/search?q=Copyright+2019

The simple fix is to just replace those two instances with the current year.

However, if you'd like to go fancier, you can try to set the year automatically to the current year by doing something like this:
https://geekthis.net/post/hugo-dynamic-copyright-year/
