### ISSUE TITLE
Inconsistent column names in SQL Workshop Activity 4

### ISSUE THREAD

**Issue by jruales** [NuevoFoundation/workshops#264]
In [SQL Workshop Activity 4](https://workshops.nuevofoundation.org/sql_workshop/activity4/), the text mentions that the galaxy table has the columns `planet` and `leader`. The video also mentions that the solution to the interactive exercise is `SELECT planet, leader FROM galaxy;`. However, the interactive exercise will only accept a solution that uses `planet_name` and `leader_name` as column names and not `planet` and `leader`.

**Comment by ozhang22** [comment]
#321
