### ISSUE TITLE
Enhancement - Update Python Turtle to use Trinket (needs testing too ;))

### ISSUE THREAD

**Issue by jeremiahjordanisaacson** [NuevoFoundation/workshops#295]
<html>
<head>
</head>
<body>
<pre>
Some notes:
1. The videos might need to be updated since they use Repl.it
2. The references to "Using Repl.it" or "Repl.it" will need to be updated.
3. The Spanish version and any other languages will need to be updated as well.

Here are the Trinket equivalents in order of the Python Turtle workshop:

=========================================================================================

PythonWithTurtleIntroduction
Uses in 2 spots:
https://workshops.nuevofoundation.org/python-turtle/using-repl-it/
https://workshops.nuevofoundation.org/python-turtle/the-basics/
<iframe src="https://trinket.io/embed/python/1363ac22be" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

=========================================================================================

PythonWithTurtleActivity1
Used here:
https://workshops.nuevofoundation.org/python-turtle/activity-1/
<iframe src="https://trinket.io/embed/python/bfe791bb1e" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

=========================================================================================

PythonWithTurtleActivity2
Used here:
https://workshops.nuevofoundation.org/python-turtle/activity-2/
<iframe src="https://trinket.io/embed/python/892913b49a" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

=========================================================================================

PythonWithTurtleActivity3
Used here:
https://workshops.nuevofoundation.org/python-turtle/activity-3/
<iframe src="https://trinket.io/embed/python/e82295e92f" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

=========================================================================================

PythonWithTurtleActivity4
Used here:
https://workshops.nuevofoundation.org/python-turtle/activity-4/
<iframe src="https://trinket.io/embed/python/c3ef894658" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

=========================================================================================

PythonWithTurtleActivity5
Used here:
https://workshops.nuevofoundation.org/python-turtle/activity-5/
<iframe src="https://trinket.io/embed/python/d83811c24a" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

=========================================================================================

PythonWithTurtleActivity6
Used here:
https://workshops.nuevofoundation.org/python-turtle/activity-6/
<iframe src="https://trinket.io/embed/python/dee0f642ce" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

=========================================================================================

PythonWithTurtleActivity7
Used here:
https://workshops.nuevofoundation.org/python-turtle/activity-7/
<iframe src="https://trinket.io/embed/python/e87cb9f3b9" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

=========================================================================================

PythonWithTurtleActivity8
Used here:
https://workshops.nuevofoundation.org/python-turtle/activity-8/
<iframe src="https://trinket.io/embed/python/b82ce0c14f" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

=========================================================================================

PythonWithTurtleActivity9
Used here:
https://workshops.nuevofoundation.org/python-turtle/activity-9/
<iframe src="https://trinket.io/embed/python/1f9c80fffe" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

=========================================================================================

PythonWithTurtleActivity10
Used here:
https://workshops.nuevofoundation.org/python-turtle/activity-10/
<iframe src="https://trinket.io/embed/python/64ab3455ae" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>
=========================================================================================

We need to talk about how to do this one:
https://workshops.nuevofoundation.org/python-turtle/activity-11/

=========================================================================================

PythonWithTurtleStudentVersion
Might just be extra, I saw this in the Repl.it folder but wasn't sure if we needed it or not. Made it, just in case for you.
<iframe src="https://trinket.io/embed/python/778f0492c9" width="100%" height="600" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

=========================================================================================
</pre>

</body>
<html>

**Comment by ozhang22** [comment]
Fixed.
