### ISSUE TITLE
Hack 2024 - Review workshops

### ISSUE THREAD

**Issue by ozhang22** [NuevoFoundation/workshops#483]
Review workshops at https://workshops.nuevofoundation.org/ or https://workshops-dev.nuevofoundation.org/ 

Examples of workshops to review that have not been reviewed extensively:

- NEW: https://workshops.nuevofoundation.org/python-earsketch/
- https://workshops-dev.nuevofoundation.org/github-basics/
- https://workshops-dev.nuevofoundation.org/ml-machine-learning/
- https://workshops.nuevofoundation.org/javascript-blocks-earsketch/
- https://workshops.nuevofoundation.org/chatbot/
- https://workshops.nuevofoundation.org/csharp-basics/

Other workshops that could be reviewed:

- https://workshops.nuevofoundation.org/python-tensorflow/
- https://workshops.nuevofoundation.org/debugging/
- https://workshops.nuevofoundation.org/supply-chain-analytics/
- https://workshops.nuevofoundation.org/kusto-kc7/
- https://workshops.nuevofoundation.org/java-datastructures/
- https://workshops.nuevofoundation.org/unity/

**Comment by sunnynagavo** [comment]
Assign this to me @ozhang22

**Comment by webreidi** [comment]
@sunnynagavo I'm working on C# basics and javascript blocks.

**Comment by sunnynagavo** [comment]
@webreidi  got it, thanks for letting me know. I will pick up GitHub basics, JavaScript and ML then.

**Comment by KavyaManocha** [comment]
I can look over the workshops under the "Other workshops that could be reviewed"

**Comment by thuang45** [comment]
@KavyaManocha which ones will you be reviewing? I can take on some of the ones you aren't doing

**Comment by aayushimodi** [comment]
I can also take some of the ones that are left!

**Comment by KavyaManocha** [comment]
> [@KavyaManocha](https://github.com/KavyaManocha) which ones will you be reviewing? I can take on some of the ones you aren't doing

I am currently doing python-tensorflow, and was also going to do kusto

**Comment by thuang45** [comment]
I can take on debugging and java data structures!
