### ISSUE TITLE
Update peaceiris/actions-hugo

### ISSUE THREAD

**Issue by peaceiris** [NuevoFoundation/workshops#56]
https://github.com/NuevoFoundation/workshops/blob/4aefafd2601151d821d1c827a531649bf418d21c/.github/workflows/main.yml#L14

This action migrated from Docker action to JavaScript (TypeScript) action. Please, check [README](https://github.com/peaceiris/actions-hugo#readme) and use [the latest version](https://github.com/peaceiris/actions-hugo/releases).

**Comment by jaellio** [comment]
Thank you for letting us know! Working on the update now.
