### ISSUE TITLE
Workshop from website is missing an image.

### ISSUE THREAD

**Issue by jeremiahjordanisaacson** [NuevoFoundation/workshops#71]
Workshop from website is missing an image:

https://workshops.nuevofoundation.org/web-basics/basics/ 

Website design
The first step in making a website is to decide which elements we want, and how they will look. This process is called layout design and it’s just a rough sketch of how the different pieces are going to come together. There are many tools to help you do this, but the oldest and one of the most popular is good ol’ pen and paper. Here’s how I sketched mine:

**![alt text](media/dog-layout-sm.png"example website for Benji”)**

This sketch is just a guideline. It’s okay to change things around as we start putting it together. A good rule of thumb is to start as simple as possible.

**Comment by jeremiahjordanisaacson** [comment]
@oliver-zhang-neuvo  @ozhang22 @Anvesha4 Just wondering if you could look into this issue. Bea is teaching tomorrow morning at 10 AM PST so it would be great if you could resolve by then. If not, no worries but just want to make you aware. Thanks!

**Comment by ozhang22** [comment]
Looks like the image shows up now.
